# action.yml
# Ref: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  release:
    description: Release of the EspressIF ESP-IDF to use.
    default: v5.1
  hash:
    description: integrity hash (sha256) of the ESP-IDF download.
    default: "1234"

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    release: ${{ inputs.release }}
    hash: ${{ inputs.hash }}
