name: 'Install Telink IDE'
description: 'Install the Eclipse based IDE required to build Telink tlsr825x projects'
inputs:
  directory:
    description: 'Directory into which to install the IDE'
    default: 'c:\telink\ide'
env:
  DRIVE: "c:"
  TLSR825X: tlsr8258
  IDE_DIR: Telink_IDE
  IDE_URI: "https://www.dropbox.com/s/ths9rev0tvhhl96/Telink_IDE.zip?dl=1"
  IDE_ZIP: Telink_IDE.zip
  IDE_HASH: "D47595AAFAE1B711A04DC83BAB08467160EA2A3559EA976576C2F8A44F47BF1F"
  IDE_EXE: TelinkSDKv1.3.1.exe

runs:
  using: "composite"
  steps:
    # Create the required directories.
    - name: Create target directoryTLSR825x base directory
      shell: pwsh
      run: |
        if (!(Test-Path ${{ inputs.directory }}-PathType container)) {
          New-Item -Path ${{ inputs.directory }} -ItemType "directory"
        )

    # Download and expand the IDE
    - name: Download the IDE
      shell: pwsh
      run: Invoke-RestMethod -Method GET -FollowRelLink -Uri "$env:IDE_URI" -OutFile "$env:TEMP\$env:IDE_ZIP"

    # Validate that the IDE has not changed.
    - name: Check IDE hash/version
      shell: pwsh
      run: |
        $Hash=$(Get-FileHash -Path "$env:DRIVE\$env:TLSR825X\$env:IDE_ZIP" -Algorithm sha256)
        if ($Hash.hash -ne $env:IDE_HASH)
        {
          Write-Warning "IDE hash has changed implying IDE update!"
          Write-Warning "Expected sha256: $env:IDE_HASH"
          Write-Warning "Actual sha256:   $(Out-String -InputObject $Hash.hash)"
        }

    - name: List IDE
      shell: pwsh
      run: Get-ChildItem -Path "$env:DRIVE\$env:TLSR825X" -Recurse

    # Note that the IDE has a path "IDE" baked into it.
    - name: Unzip the IDE
      shell: pwsh
      run: Expand-Archive -Path "$env:TEMP\$env:IDE_ZIP" -DestinationPath "$env:TEMP"
    - name: Delete IDE Zipfile
      shell: pwsh
      run: Remove-Item -Path "$env:TEMP\$env:IDE_ZIP"

    - name: List IDE
      shell: pwsh
      run: Get-ChildItem -Path "$env:TEMP\IDE" -Recurse

    - name: Report the IDE version and spot multiple unexpected EXEs.
      shell: pwsh
      run: |
        $exes=Get-ChildItem -Path $env:TEMP\IDE\telink*.exe | Select FullName
        if ($exes.count > 1) {
          Write-Error "Multiple executables were found that could be IDE installers"
          Get-ChildItem -Path "$env:TEMP\IDE\telink*.exe
          exit 1
        }
        $version="unknown"
        if ($exes[0].FullName -match '(v\d+\.\d+\.\d+)') {
          $version=$Matches[0]
        }
        Write-Info "Telink IDE version: $version"

    # Note the strange single-quote syntax required for the call operator.
    - name: Install the IDE
      shell: pwsh
      run: |
        $exes=Get-ChildItem -Path "$env:TEMP\IDE\telink*.exe"
        '& $exes[0].FullName /VERYSILENT /SUPPRESSMSGBOXES /DIR=$inputs.directory /NOICONS /LOG=$env:TEMP\install.log'
        Get-Content -Path "$env:DRIVE\$env:TLSR825X\$env:IDE_DIR\IDE\install.log"

    - name: List IDE
      shell: pwsh
      run: Get-ChildItem -Path "$inputs.directory"
