name: 'Install Telink Zigbee SDK'
description: 'Install the Zigbee SDK required to build Telink tlsr825x projects'
inputs:
  directory:
    description: 'Directory into which to install the Zigbee SDK'
    default: 'c:\telink\zigbee_sdk'
env:
  SDK_DIR: sdk
  SDK_URI: "http://wiki.telink-semi.cn/tools_and_sdk/Zigbee/Zigbee_SDK.zip"
  SDK_ZIP: Zigbee_SDK.zip
  SDK_HASH: "AD3C28FC2A50E9D550B933335FD96CE2A58EECDD602DEB451FCC54087947E01C"

runs:
  using: "composite"
  steps:
    # Create the required directories.
    - name: Create target directory
      shell: pwsh
      run: |
        if (!(Test-Path ${{ inputs.directory }} -PathType container)) {
          New-Item -Path ${{ inputs.directory }} -ItemType "directory"
        }

    # Download and expand the SDK.
    - name: Download the Zigbee SDK
      shell: pwsh
      run: Invoke-RestMethod -Method GET -FollowRelLink -Uri "$env:SDK_URI" -OutFile "$env:TEMP\$env:SDK_ZIP"

    # Validate that the Zigbee SDK has not changed.
    - name: Check SDK hash/version
      shell: pwsh
      run: |
        $Hash=$(Get-FileHash -Path "$env:TEMP\$env:SDK_ZIP" -Algorithm sha256)
        if ($Hash.hash -ne $env:SDK_HASH)
        {
          Write-Warning "Zigbee SDK hash has changed implying Zigbee SDK update!"
          Write-Warning "Expected sha256: $env:SDK_HASH"
          Write-Warning "Actual sha256:   $(Out-String -InputObject $Hash.hash)"
        }

    - name: Unzip the SDK
      shell: pwsh
      run: Expand-Archive -Path "$env:TEMP\$env:SDK_ZIP" -DestinationPath "${{ inputs.directory }}"

    - name: Delete SDK Zipfile
      shell: pwsh
      run: Remove-Item -Path "$env:TEMP\$env:SDK_ZIP"

    - name: List SDK
      shell: pwsh
      run: Get-ChildItem -Path "${{ inputs.directory }}"
