on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to create a TLSR825x IDE environment.
    steps:
      # Download the IDE.
      - name: Create working directory
        run: New-Item -Path "c:\" -Name "tlsr825x" -ItemType "directory"
      - name: Download the IDE
        run: Invoke-RestMethod -Method GET -FollowRelLink -Uri https://www.dropbox.com/s/ths9rev0tvhhl96/Telink_IDE.zip?dl=1 -OutFile c:\tlsr825x\Telink_IDE.zip
      - name: Unzip the IDE
        run: Expand-Archive -Path c:\tlsr825x\Telink_IDE.zip -DestinationPath c:\tlsr825x