on: [push]

env:
  DRIVE: "c:"
  TLSR825X: tlsr8258
  IDE_DIR: IDE
  SDK_DIR: sdk
  IDE_URI: "https://www.dropbox.com/s/ths9rev0tvhhl96/Telink_IDE.zip?dl=1"
  IDE_ZIP: Telink_IDE.zip
  IDE_HASH: "D47595AAFAE1B711A04DC83BAB08467160EA2A3559EA976576C2F8A44F47BF1F"
  IDE_EXE: TelinkSDKv1.3.1.exe
  SDK_URI: "http://wiki.telink-semi.cn/tools_and_sdk/Zigbee/Zigbee_SDK.zip"
  SDK_ZIP: Zigbee_SDK.zip
  SDK_HASH: "AD3C28FC2A50E9D550B933335FD96CE2A58EECDD602DEB451FCC54087947E01C"

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to create a TLSR825x IDE environment.
    steps:
      # Create the required directories.
      - name: Create TLSR825x base directory
        run: New-Item -Path "$env:DRIVE\" -Name "$env:TLSR825X" -ItemType "directory"
      - name: Create TLSR825x SDK directory
        run: New-Item -Path "$env:DRIVE\$env:TLSR825X" -Name "$env:SDK_DIR" -ItemType "directory"

      # Download and expand the IDE
      - name: Download the IDE
        run: Invoke-RestMethod -Method GET -FollowRelLink -Uri "$env:IDE_URI" -OutFile "$env:DRIVE\$env:TLSR825X\$env:IDE_ZIP"
      # Validate that the IDE has not changed.
      - name: Check IDE hash/version
        run: |
          $Hash=$(Get-FileHash -Path "$env:DRIVE\$env:TLSR825X\$env:IDE_ZIP" -Algorithm sha256)
          if ($Hash.hash -ne $env:IDE_HASH)
          {
            Write-Warning "IDE hash has changed implying IDE update!"
            Write-Warning "Expected sha256: $env:IDE_HASH"
            Write-Warning "Actual sha256:   $(Out-String -InputObject $Hash.hash)"
          }
      # Note that the IDE has a path "IDE" baked into it.
      - name: Unzip the IDE
        run: Expand-Archive -Path "$env:DRIVE\$env:TLSR825X\$env:IDE_ZIP" -DestinationPath "$env:DRIVE\$env:TLSR825X"
      - name: Delete IDE Zipfile
        run: Remove-Item -Path "$env:DRIVE\$env:TLSR825X\$env:IDE_ZIP"
      # Note the strange single-quote syntax required for the call operator.
      - name: Install the IDE
        run: '& $env:DRIVE\$env:TLSR825X\$env:IDE_DIR\$env:IDE_EXE'
      - name: List IDE
        run: Get-ChildItem -Path "$env:DRIVE\$env:TLSR825X\$env:IDE_DIR"

      # Download and expand the SDK.
      - name: Download the Zigbee SDK
        run: Invoke-RestMethod -Method GET -FollowRelLink -Uri "$env:SDK_URI" -OutFile "$env:DRIVE\$env:TLSR825X\$env:SDK_DIR\$env:SDK_ZIP"
      # Validate that the Zigbee SDK has not changed.
      - name: Check SDK hash/version
        run: |
          $Hash=$(Get-FileHash -Path "$env:DRIVE\$env:TLSR825X\$env:SDK_DIR\$env:SDK_ZIP" -Algorithm sha256)
          if ($Hash.hash -ne $env:SDK_HASH)
          {
            Write-Warning "Zigbee SDK hash has changed implying Zigbee SDK update!"
            Write-Warning "Expected sha256: $env:SDK_HASH"
            Write-Warning "Actual sha256:   $(Out-String -InputObject $Hash.hash)"
          }
      - name: Unzip the SDK
        run: Expand-Archive -Path "$env:DRIVE\$env:TLSR825X\$env:SDK_DIR\$env:SDK_ZIP" -DestinationPath "$env:DRIVE\$env:TLSR825X\$env:SDK_DIR"
      - name: Delete SDK Zipfile
        run: Remove-Item -Path "$env:DRIVE\$env:TLSR825X\$env:SDK_DIR\$env:SDK_ZIP"
      - name: List SDK
        run: Get-ChildItem -Path "$env:DRIVE\$env:TLSR825X\$env:SDK_DIR"

      - name: Find eclipsec.exe
        run: Get-ChildItem -Path "c:\telink*"

      - name: Find the workspace files
        run: Get-ChildItem -Path "$env:DRIVE\$env:TLSR825X\$env:SDK_DIR\tlsr_tc32" -Recurse

      # -name: Build TLSR8258 ZigBee image
      #  run: |
      #   eclipsec `
      #   -vm c:\Users\PDS\TelinkSDK\jre\bin\client `
      #   -noSplash `
      #   -application org.eclipse.cdt.managedbuilder.core.headlessbuild  `
      #   -data C:\Users\PDS\telink\workspaces  `
      #   -build tl_zigbee_sdk/sampleGW_8258
