on: [push]

env:
  DRIVE: "c:"
  TLSR825X: tlsr8258
  IDE_DIR: ide
  SDK_DIR: sdk
  IDE_URI: "https://www.dropbox.com/s/ths9rev0tvhhl96/Telink_IDE.zip?dl=1"
  IDE_ZIP: Telink_IDE.zip
  SDK_URI: "http://wiki.telink-semi.cn/tools_and_sdk/Zigbee/Zigbee_SDK.zip"
  SDK_ZIP: Zigbee_SDK.zip

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to create a TLSR825x IDE environment.
    steps:
      # Download the IDE.
      - name: Create TLSR825x base directory
        run: New-Item -Path "%DRIVE%\" -Name "%TLSR825X%" -ItemType "directory"
      - name: Create TLSR825x IDE directory
        run: New-Item -Path "%DRIVE%\%TLSR825X%" -Name "%IDE_DIR%" -ItemType "directory"
      - name: Create TLSR825x SDK directory
        run: New-Item -Path "%DRIVE%\%TLSR825X%" -Name "%SDK_DIR%" -ItemType "directory"
      - name: Download the IDE
        run: Invoke-RestMethod -Method GET -FollowRelLink -Uri "%IDE_URI%" -OutFile "%DRIVE%\%TLSR825X%\%IDE_DIR%\%IDE_ZIP%"
      - name: Unzip the IDE
        run: Expand-Archive -Path "%DRIVE%\%TLSR825X%\%IDE_DIR%\%IDE_ZIP%" -DestinationPath "%DRIVE%\%TLSR825X%\%IDE_DIR%"
      - name: Delete IDE Zipfile
        run: Remove-Item -Path "%DRIVE%\%TLSR825X%\%IDE_DIR%\%IDE_ZIP%"
      - name: List IDE
        run: Get-ChildItem -Path "%DRIVE%\%TLSR825X%\%IDE_DIR%"
      - name: Download the SDK
        run: Invoke-RestMethod -Method GET -FollowRelLink -Uri "%SDK_URI%" -OutFile "%DRIVE%\%TLSR825X%\%SDK_DIR%\%SDK_ZIP%"
      - name: Unzip the SDK
        run: Expand-Archive -Path "%DRIVE%\%TLSR825X%\%SDK_DIR%\%SDK_ZIP%" -DestinationPath "%DRIVE%\%TLSR825X%\%SDK_DIR%"
      - name: Delete SDK Zipfile
        run: Remove-Item -Path "%DRIVE%\%TLSR825X%\%SDK_DIR%\%SDK_ZIP%"
      - name: List SDK
        run: Get-ChildItem -Path "%DRIVE%\%TLSR825X%\%SDK_DIR%"
